# gen_deltat.py — USNO 관측 ΔT 3종 파일 → JS 테이블
#  historic_deltat.data : 1657.0 ~ 1984.5 (0.5년 간격, TDT-UT1)
#  deltat.data          : 1973-02 ~ 최신 (월 1일, TT-UT)
#  deltat.preds         : 예측 (분기)
# 출처: https://maia.usno.navy.mil/ser7/{historic_deltat.data, deltat.data, deltat.preds}
import json

hist = []
for i, ln in enumerate(open('historic_deltat.data', encoding='utf-8')):
    p = ln.split()
    if len(p) < 2: continue
    try: y = float(p[0]); v = float(p[1])
    except ValueError: continue
    hist.append([y, v])

modern = []
for ln in open('deltat.data', encoding='utf-8'):
    p = ln.split()
    if len(p) != 4: continue
    y, m, d, v = int(p[0]), int(p[1]), int(p[2]), float(p[3])
    yr = y + (m - 1 + (d - 1) / 30.0) / 12.0
    modern.append([round(yr, 6), v])

preds = []
for ln in open('deltat.preds', encoding='utf-8'):
    p = ln.split()
    if len(p) < 3: continue
    try: yr = float(p[1]); v = float(p[2])
    except ValueError: continue
    preds.append([yr, v])

# 병합: 관측 우선(1973.08 이후 modern), 그 이전 historic, 마지막 관측 이후 preds
cut_modern = modern[0][0]
cut_pred = modern[-1][0]
merged = [r for r in hist if r[0] < cut_modern] + modern + [r for r in preds if r[0] > cut_pred]
merged.sort(key=lambda r: r[0])
# 중복 제거
out = []
for r in merged:
    if out and abs(r[0] - out[-1][0]) < 1e-9: out[-1] = r
    else: out.append(r)

js = ("// AUTO-GENERATED by gen_deltat.py — USNO ser7 관측/예측 ΔT\n"
      "// historic_deltat.data(1657~1984) + deltat.data(1973~%s) + deltat.preds(~%s)\n"
      "'use strict';\nmodule.exports = %s;\n" % (
          modern[-1][0], preds[-1][0], json.dumps(out, separators=(',', ':'))))
open('deltat-obs.js', 'w', encoding='utf-8').write(js)
print("hist=%d modern=%d preds=%d merged=%d range=%.3f~%.3f bytes=%d"
      % (len(hist), len(modern), len(preds), len(out), out[0][0], out[-1][0], len(js)))
print("샘플:", out[0], out[len(out)//2], [r for r in out if abs(r[0]-2024.0)<0.05], out[-1])
