# gen_data.py — VSOP87D(Earth) + IAU1980 장동 계수를 PyMeeus 에서 추출해 JS 데이터로 고정
# 출처: pymeeus 0.5.12 (site-packages/pymeeus/Earth.py, Coordinates.py)
#   Earth.VSOP87_L / VSOP87_B / VSOP87_R : [ [A, B, C], ... ] , A 단위 1e-8 rad
#   Coordinates.NUTATION_ARG_TABLE / NUTATION_SINE_COEF_TABLE : IAU1980 63항
import json, sys
from pymeeus import Earth
from pymeeus.Coordinates import NUTATION_ARG_TABLE, NUTATION_SINE_COEF_TABLE, NUTATION_COSINE_COEF_TABLE

THRESH = float(sys.argv[1]) if len(sys.argv) > 1 else 0.0   # |A| 절단 임계 (1e-8 rad)

def pack(series):
    out = []
    for s in series:
        out.append([[float(a), float(b), float(c)] for (a, b, c) in s if abs(a) >= THRESH])
    return out

L = pack(Earth.VSOP87_L)
B = pack(Earth.VSOP87_B)
R = pack(Earth.VSOP87_R)

data = {
    "_meta": {
        "source": "PyMeeus 0.5.12 — pymeeus/Earth.py (VSOP87D Earth), pymeeus/Coordinates.py (IAU1980 nutation)",
        "unitsL": "A in 1e-8 rad ; argument = B + C*tau, tau = julian millennia from J2000 (TT)",
        "threshold": THRESH,
        "counts": {"L": [len(x) for x in L], "B": [len(x) for x in B], "R": [len(x) for x in R],
                   "nutation": len(NUTATION_ARG_TABLE)},
    },
    "L": L, "B": B, "R": R,
    "nutArg": [list(map(int, r)) for r in NUTATION_ARG_TABLE],
    "nutSin": [[float(v[0]), float(v[1])] for v in NUTATION_SINE_COEF_TABLE],
    "nutCos": [[float(v[0]), float(v[1])] for v in NUTATION_COSINE_COEF_TABLE],
}
js = "// AUTO-GENERATED by gen_data.py — DO NOT EDIT\n" \
     "'use strict';\nmodule.exports = " + json.dumps(data, separators=(",", ":")) + ";\n"
open("vsop87-earth.js", "w", encoding="utf-8").write(js)
print("counts L=%s B=%s R=%s nut=%d" % (data["_meta"]["counts"]["L"],
      data["_meta"]["counts"]["B"], data["_meta"]["counts"]["R"], len(NUTATION_ARG_TABLE)))
print("bytes =", len(js))
